services:
  - type: web
    name: user-service
    plan: free
    runtime: docker
    region: oregon        # optional—ensure same region as the database
    repo: https://github.com/your-username/your-repo
    rootDir: ./user-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: user-db
          property: connectionString
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: user-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: user-db
          property: password
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: user-db
    plan: free
    region: oregon        # ensure same region to enable private networking
