# render.yaml - Place this in the root of your Git repository

# Top-level key for all database definitions
databases:
  - name: user-db # The name to reference in other services
    plan: free # Use the free instance type
    databaseName: postgres # The name of the actual database
    user: postgres # The username for the database

# Top-level key for all application service definitions
services:
  - type: web # A web service accessible from the internet
    name: user-service # The name of your microservice
    runtime: java
    plan: free
    # --- Build Configuration ---
    repo: https://github.com/Prime-Systems/primedealer-backend # The URL to your repo
    rootDir: ./user-service # Specifies the submodule directory
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/user-service-0.0.1-SNAPSHOT.jar"
    # --- Environment Configuration ---
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: user-db # Correctly links to the database defined above
          property: connectionString
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: user-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: user-db
          property: password
      - key: JWT_SECRET_KEY
        generateValue: true