name: User Service CI/CD

on:
  push:
    paths:
      - 'user-service/**'
    branches:
      - '**'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: primedealer-user-service
  WORKING_DIRECTORY: ./user-service

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Ensure mvnw is executable
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: chmod +x mvnw

      - name: Build and Push Docker image to ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_IMAGE_URI="$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest"
          echo "Building Docker image: $ECR_IMAGE_URI"

          ./${{ env.WORKING_DIRECTORY }}/mvnw -f ${{ env.WORKING_DIRECTORY }}/pom.xml spring-boot:build-image \
            -Dspring-boot.build-image.imageName="$ECR_IMAGE_URI"

          docker push "$ECR_IMAGE_URI"
          echo "ECR_IMAGE_URI=$ECR_IMAGE_URI" >> $GITHUB_ENV

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull $ECR_IMAGE_URI

            echo "Starting Postgres container (if not running)..."
            docker ps -a | grep user-db || \
              docker run -d --name user-db \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=postgres \
              -e POSTGRES_DB=postgres \
              -p 5432:5432 \
              postgres:17-alpine

            echo "Stopping existing app container (if running)..."
            docker stop user-service || true
            docker rm user-service || true

            echo "Starting new app container..."
            docker run -d --name user-service \
              -p 8081:8081 \
              -e DB_URL=jdbc:postgresql://localhost:5432/postgres \
              -e DB_USERNAME=postgres \
              -e DB_PASSWORD=postgres \
              $ECR_IMAGE_URI
