name: User Service CI/CD

on:
  push:
    paths:
      - 'user-service/**'
    branches:
      - '**'

env:
  # Define ECR and AWS settings
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: primedealer-user-service
  ECS_STACK_NAME: primedealer-user-service
  ECS_TEMPLATE_FILE: ./deployment/user-service-ecs.yml
  WORKING_DIRECTORY: ./user-service

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Ensure mvnw is executable
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: chmod +x mvnw

      # --- REVISED BUILD AND PUSH LOGIC ---
      - name: Build, and Push Docker image to ECR
        run: |
          # 1. Construct the full ECR image URI
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_IMAGE_URI="$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest"
          echo "Image will be built and tagged as: $ECR_IMAGE_URI"

          # 2. Build the image directly with the final ECR name
          #    Note the change in working directory for the mvnw command
          ./${{ env.WORKING_DIRECTORY }}/mvnw -f ${{ env.WORKING_DIRECTORY }}/pom.xml spring-boot:build-image \
            -Dspring-boot.build-image.imageName="$ECR_IMAGE_URI"
          
          # 3. Push the newly built image to ECR
          echo "Pushing image to ECR..."
          docker push "$ECR_IMAGE_URI"

          # 4. Store the ECR URI for the deploy step
          echo "ECR_IMAGE_URI=$ECR_IMAGE_URI" >> $GITHUB_ENV

      - name: Deploy to AWS ECS using CloudFormation
        run: |
          aws cloudformation deploy \
            --stack-name ${{ env.ECS_STACK_NAME }} \
            --template-file ${{ env.ECS_TEMPLATE_FILE }} \
            --parameter-overrides \
              ImageURI=${{ env.ECR_IMAGE_URI }} \
              VpcId=${{ secrets.VPC_ID }} \
              SubnetIds='${{ secrets.SUBNET_IDS }}' \
              SecurityGroupIds='${{ secrets.SECURITY_GROUP_IDS }}' \
            --capabilities CAPABILITY_NAMED_IAM